# Generated by Django 4.2 on 2023-07-25 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0018_emprestimos_alter_categoria_nome_delete_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 15, 26, 27, 816706)),
        ),
    ]
