# Generated by Django 4.2 on 2023-04-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuarios',
            new_name='id_usuario',
        ),
    ]
